### ISSUE TITLE
Make the table look *exactly* like a PSR

### ISSUE THREAD

**Issue by twgardner2** [twgardner2/navy_psr#23]
I got this feedback from multiple people this weekend. The table was always intended to be the bridge between how people are currently used to looking at PSRs and my new way of doing it. I just never took the time to make the table look *exactly* like a PSR because it's not going to be fun. 

Thoughts?

**Comment by ChaseWPDEV** [comment]
Suggestion close and consolidate with #25

**Comment by twgardner2** [comment]
Yes, agreed.
