### ISSUE TITLE
Explain Solid and Dashed Lines in Legend

### ISSUE THREAD

**Issue by twgardner2** [twgardner2/navy_psr#36]

**Comment by ChaseWPDEV** [comment]
Idea: Dashed lines --as currently used-- are dumb (there just shouldn't be lines there). Instead, maybe dashed lines should be used for connecting "no RSCA" entries since no trend information should be concluded from those entries.

**Comment by twgardner2** [comment]
I don't entirely disagree, but I think experienced board member want to see it. Also, when I had the email chain going with the civilian guy running the board processes working group, he really wanted it there. Doesn't mean we can't take them off, just more information...
